fos_comment:
    db_driver: orm
    class:
        model:
            comment: Application\Sonata\NewsBundle\Entity\Comment
            thread:   Application\Sonata\NewsBundle\Entity\Post
    form:
        comment:
            type: sonata_comment_comment