#
# more information can be found here https://sonata-project.org/bundles/news
#
sonata_news:
    class:
        
        
        post:         Application\Sonata\NewsBundle\Entity\Post
        
        tag:          Application\Sonata\ClassificationBundle\Entity\Tag
        #category:     Application\Sonata\ClassificationBundle\Entity\Category
        collection:   Application\Sonata\ClassificationBundle\Entity\Collection
        media:        Application\Sonata\MediaBundle\Entity\Media
        #context:      Application\Sonata\ClassificationBundle\Entity\Context
        #comment:      Application\Sonata\NewsBundle\Entity\Comment
        user:         Application\Sonata\UserBundle\Entity\User
        

    title:        %sonata_news.blog_title%
    link:         %sonata_news.blog_link%
    description:  %sonata_news.blog_description%
    salt:         %sonata_news.salt%

    # permalink_generator: sonata.news.permalink.category # /party/new-year
    permalink_generator: sonata.news.permalink.date # /2011/12/31/new-year

    # comment options
    comment:
        notification:
            emails:   %sonata_news.comment.emails%
            from:     %sonata_news.comment.email_from%
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'


# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNewsBundle: ~